GET localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWtoaWxAZ21haWwuY29tIiwibmJmIjoxNjQyNjU1MDQ2LCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoibW4tamRiYy1hdXRoIiwibGFuZ3VhZ2UiOiJlbiIsImV4cCI6MTY0MjY1ODY0NiwiaWF0IjoxNjQyNjU1MDQ2LCJoYWlyX2NvbG9yIjoiQnJvd24ifQ.o-N06-NMTIr__X_eFGBSopjz8wRiTxQiaREuxpM-3jU